name: Log Time Job
on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
jobs:
  log_time:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run logging script
      run: |
        chmod +x log_time.sh
        ./log_time.sh

    - name: Commit and push changes
      run: |
        git config user.name "Acey32118"
        git config user.email "pacevgalima@gmail.com"
        git pull --rebase
        if ! git diff --quiet; then
            git add log.txt
            git commit -m "Update log file with new timestamp"
            git push
        fi
